### ISSUE TITLE
《需求文档》继续细化面向用户的需求建模

### ISSUE THREAD

**Issue by CNLHC** [buaaembeddedse/shattuckite-META#10]
文档仓库[shattuckite-doc](https://github.com/buaaembeddedse/shattuckite-doc/tree/PRD-dev)的`PRD-dev`分支内正在进行需求文档的编写。

请参考`/requirements/source/userOriented/intro.rst`文件内的概述信息，并自行扮演用户的角色，完成面向用户的需求建模。

#### 修改建议

1.  `查看监控数据` 用例拆分

该用例至少可进一步拆分为 `查看实时监控数据` 及 `查看历史数据`。

2.  `管理传感器` 用例重新设计

管理传感器实际应为管理 `设备` 。 `设备` 包括`传感器` ,`执行器` , `摄像头` 等本系统可能会用到的物理设备。

管理设备请细分为`批量设备管理` ，`传感器管理`  `执行器管理`等

3.  添加`操作执行器`的用例

用户可能会直接操作隶属于`执行器`类的设备。**操作** 与 **管理** 属于不同的逻辑，应当为操作执行器单独设计用例。

4. 关于`prerequisites`字段

该字段主要体现用例的相互依赖关系。例如在`A`用例的`prerequisites`字段中列出`B`用例，则说明`A`用例一定要在用户执行了`B`用例后才会执行。 目前部分用例该字段有些许不妥，请修改。

5. 关于`case.json` 文件编辑

[9](https://github.com/buaaembeddedse/shattuckite-META/issues/9)  中提交的`case.json`版本存在些许语法错误。建议使用带有`json lint`功能的编辑器对本文件进行编辑。

该任务计`100KPI`

该任务应当在`2019年3月20日24:00`前完成。

**Comment by mqlKKK** [comment]
文档已经在 https://github.com/buaaembeddedse/shattuckite-doc/commit/6dccfdca5115903c334e38f9d3483930b02f78c5 中完成
