### ISSUE TITLE
前端开发-移动端UI原型设计

### ISSUE THREAD

**Issue by CNLHC** [buaaembeddedse/shattuckite-META#13]
---
KPI: 200
DDL: 2019/3/30 24:00
---

根据需求文档的描述，进行移动端用户界面的原型。设计UI时请注意:

1. 使用 `Axure` 原型工具进行绘制
2. 最终产品需要严格按照本版原型进行开发，在设计时请考虑可实现性。
3. 尽可能cover用户可见的每一个页面
4. 尽量保证设计的美观
5. 在buaase下新建仓库`shattuckite-gui-mobile`,并将设计稿提交到该仓库。

此外，如果时间允许的话，请为UI原型添加简单的交互逻辑。

注: [Antd library](https://library.ant.design/) 提供`ant-design`及`ant-design-mobile`组件的Axure模型。

**Comment by CNLHC** [comment]
@mqlKKK 请指出相关commit记录

**Comment by mqlKKK** [comment]
模型已经在 https://github.com/buaaembeddedse/shattuckite-gui/commit/466904f7b74d0ea34fdb62cae296740a95c6f45e 中完成
