### ISSUE TITLE
前端开发-移动端UI设计-第二期

### ISSUE THREAD

**Issue by CNLHC** [buaaembeddedse/shattuckite-META#15]
继续使用 `Axure` 进行移动端原型设计

#### 与用例分析联动

修改 [shattuckite-doc](https://github.com/buaaembeddedse/shattuckite-doc) 仓库 `PRD-dev`分支下记载用例的`case.json`文件，对于每一个用例，添加一个新的字段`mobileGUI`，用于记录与该用例相关的原型界面设计文件。`mobileGUI`字段存储一个`原型页面对象(PageObj)`列表。一个`PageObj`包括以下字段

1. pageName(String): 字符串，表示`Axure`中该页面名称
2. subPage(Union[PageObj[],String]): 原型页面对象列表，存储 **与本用例有关的** ，且为该页面子页面的页面。当子页面不再嵌套其它子页面时，可仅用PageName表述一个子页面。

此外请注意,为了保证最大的兼容性,请将`Axure`页面名称全部改为英文.

一个简单的示例

```
"mobileGUI":[
    { 
        "pageName":"login",
        "subPage":["login_wrongInfo"]
    },
    {
        "pageName":"index",
        "subPage":[
            {
                pageName:"data",
                subPage:["historyData","realtimeData"]
            }
        ]
    }
]
```

#### 添加简单的交互功能

请为原型页面添加易于实现的交互逻辑。

页面间的跳转是一个典型的交互逻辑。例如`主界面`中的`监控数据按钮`，可以添加`onClick`回调，实现在原型输出文件中点击该按钮可以跳转到`监控数据`页面中。

本次任务中请至少为所有的跳转按钮添加页面跳转交互逻辑。其他的交互逻辑请视情况添加。

#### 提升美观性

请参考 

1. [Martial Design](https://material.io/design/)
2. [Ant Design Guidelines](https://ant.design/docs/spec/introduce) 

等成文的设计规范，**尽量** 改善UI的表现力，提高界面美观程度。

**Comment by CNLHC** [comment]
@mqlKKK 请给出该问题相关的commit记录，然后重新关闭该问题

**Comment by mqlKKK** [comment]
模型已经在 https://github.com/buaaembeddedse/shattuckite-gui/commit/6aab973425df89fdfc40ca87fcc01e05d71fea31 中完成
