### ISSUE TITLE
《需求文档》中uml图逻辑上的优化

### ISSUE THREAD

**Issue by wenguang1998** [buaaembeddedse/shattuckite-META#19]
以下两种逻辑模式的取舍
![实时监控数据](https://user-images.githubusercontent.com/44225816/58238980-cd93ac00-7d7a-11e9-87f4-ae3fe1d465d7.png)
![实时监控数据1](https://user-images.githubusercontent.com/44225816/58238996-d2586000-7d7a-11e9-91a1-fd5da6fca3a2.png)

**Comment by wenguang1998** [comment]
最终采用第一种格式的编写规格，之后的全部应用场景都采用第一种风格的编写规格

**Comment by wenguang1998** [comment]
理由：stop节点的意义就被理解为程序或者模块非正常使用的输出结果，正常使用的话是不会退出模块的

**Comment by wenguang1998** [comment]
之后发现部分场景需要根据具体的情况进行分析，例如存在多个终止节点的时候，如果统一使用一个终止节点的话会变得非常不美观，在这一点上我也进行了修改，以下只是一个例子，展示前后对比
**前：**
![历史监控数据](https://user-images.githubusercontent.com/44225816/58281273-52131880-7dd5-11e9-9f11-ff5794e57c71.png)
**后：**
![历史监控数据](https://user-images.githubusercontent.com/44225816/58281292-63f4bb80-7dd5-11e9-8f75-58a2ab80e580.png)
当然这个好像并不太明显，但我还是觉得第二种更加美观。还请给出相应的意见

**Comment by CNLHC** [comment]
可以采用第二种方式
