### ISSUE TITLE
React+Redux 前端: UI框架 前端路由与scss样式

### ISSUE THREAD

**Issue by CNLHC** [buaaembeddedse/shattuckite-META#5]
#### 1. 使用 `antd` 提供的组件 对 #4  与 #1  中的用户交互组件进行美化。
(主要是替换按钮/输入框/列表等组件)

#### 2. 使用 `scss` 为组件提供简单的样式。
注意，可能需要改变Webpack配置文件。如果是用`create-react-app`生成的项目需要`eject`操作。

#### 3. 使用 `React-Router`编写前端路由，实现
a. 设计一个主界面，主界面上有连接到TickTocToe 和 TodoList的按钮
b. 在`TickTocToe`和`TodoList`的页面上分别加上返回主界面的按钮
c. 请使用`Hash-Router`

此外，关于一些代码组织上的建议

1. 组件源代码主要存储在`src/container` 和`src/presentation`下; `Reducer.ts(Root)`, `index.tsx`等存放在`src/` 下
2. 每个组件拥有自己的独立文件夹
3. 所有组件的主类均在文件夹内的`index.tsx`文件实现与导出
4. 对于容器组件，文件夹内，除了`index.tsx`外，通常情况下还会拥有`action.ts`和`reducers.ts`
5. 如果需要添加样式的话，可以在组件所属的文件夹内添加`index.scss`

**Comment by mqlKKK** [comment]
示例已经在 https://github.com/mqlKKK/react-router 中完成
