### ISSUE TITLE
《需求文档》面向用户的需求建模编写

### ISSUE THREAD

**Issue by CNLHC** [buaaembeddedse/shattuckite-META#9]
文档仓库[shattuckite-doc](https://github.com/buaaembeddedse/shattuckite-doc/tree/PRD-dev)的`PRD-dev`分支内正在进行需求文档的编写。

请参考`/requirements/source/userOriented/intro.rst`文件内的概述信息，并自行扮演用户的角色，完成面向用户的需求建模。

在编写用例时，应当编辑`/requirements/source/userOriented/case.json`文件。该文件内已经设计了两个用例供参考。

请尽可能多的提出需求并以标准化用例的形式记录。

该任务计`100KPI`

该任务应当在`2019年3月17日24:00`前完成。

**Comment by mqlKKK** [comment]
文档已经在 https://github.com/buaaembeddedse/shattuckite-doc/commit/89e91eed8cc1c2b889661e6ddd79581090330be8 中完成
